name: Teste de Gatilho Manual

on:
  workflow_dispatch: # Apenas o gatilho manual

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Apenas um teste de echo
        run: echo "O gatilho workflow_dispatch funcionou!"
